<html lang="ch">
<head>
    <title>App Name - Page Title</title>
</head>
<body>

<h1><?=$v($title)?></h1>
<p>This is appended to the master sidebar.</p>

<div class="container">
    <p>This is my body content.</p>
    <?php foreach($list as $item): ?>
    <a href="/new/<?=$v($item['id'])?>">
        <?=$v($item['title'])?>
    </a>
    <br/>
    <?=$v($item['content'])?>
    <?php endforeach ?>
    <br/>

    最新资讯：
    <br/>

    <?php foreach($news as $new): ?>
    <a href="/new/<?=$v($new['id'])?>">
        <?=$v($new['title'])?>
    </a>
    <br/>
    <?php endforeach ?>
</div>
</body>
</html>
